version: '3'

services:
  web:
    image: nginx:1-alpine
    restart: always
    volumes:
      - html:/usr/share/nginx/html
    networks:
      frontend:

networks:
  frontend:
    external:
      name: proxy_frontend

volumes:
  html:
