services:

  web:
    image: nginx:1.27-alpine
    restart: always
    volumes:
      - html:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      frontend:

volumes:
  html:

networks:
  frontend:
    name: proxy_frontend
    external: true
