services:

  web:
    image: nginx:1-alpine
    restart: always
    network_mode: "host"
    volumes:
      - html:/usr/share/nginx/html
      - certbot:/var/www/certbot/:ro
      - certs:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:v1.29.0
    volumes:
      - certbot:/var/www/certbot
      - certs:/etc/letsencrypt

volumes:
  html:
  certbot:
  certs:
